### ISSUE TITLE
Autotick bot not working with this repo

### ISSUE THREAD

**Issue by mfisher87** [conda-forge/quarto-feedstock#14]
Not sure where to start. Documentation is a bit light.

https://github.com/regro/cf-scripts suggests that we need to create a file called `autotick-bot/please.go`, but I see lots of other repositories getting autotick PRs without that file, for example [protobuf](https://github.com/conda-forge/protobuf-feedstock). protobuf also gets release from GitHub, but instead of using a "release", like us, they fetch an archive (`https://github.com/protocolbuffers/protobuf/archive/refs/tags/v{{ version }}.tar.gz`). Is that the key to getting this working?

**Comment by mfisher87** [comment]
https://github.com/conda-forge/quarto-feedstock/pull/16#issuecomment-1559468997

@msarahan do you have any ideas? If not, I'll start digging around in the bot code and try to update the docs for the bot with what I learn.

**Comment by mfisher87** [comment]
A very helpful comment here: https://github.com/conda-forge/quarto-feedstock/pull/16#issuecomment-1668921124

**Comment by mfisher87** [comment]
Autotick bot was disabled in https://github.com/conda-forge/quarto-feedstock/pull/48

**Comment by cderv** [comment]
@mfisher87 Is the autotick bot responsible to open new PR for new build ? 

We have a new 1.4 build to release, should we do it manually ?

**Comment by mfisher87** [comment]
Yeah, let's do that manually. There are two ways to use bots to open PRs: The autotick bot, which is disabled because it can only do 1.5 releases (context linked from this thread), and the bots that respond to manual commands. The issue with the manual commands is the same, we can't [ask the bot for a specific release](https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-update-version). Or if we can I don't know how ;)

Might be able to look at it this weekend.

**Comment by cderv** [comment]
If the autotick bot is not working, it means we need to do manual PR in a fork to update the conda package to latest version ? 

We have a security patch (1.4.557) to release, and 1.5 version will be released soon. So I am preparing for this

**Comment by mfisher87** [comment]
I'm going to take on releasing the latest patch version as I'm impacted by a bug with figure alt-text :)

**Comment by mfisher87** [comment]
Bot's working fine now!
