### ISSUE TITLE
TinyTeX installation breaks conda environments

### ISSUE THREAD

**Issue by mfisher87** [conda-forge/quarto-feedstock#23]
Currently getting TeX Live/TinyTex installed with the conda-forge `quarto` package isn't the best experience.

`quarto install tinytex` results in my Quarto installation being replaced with TinyTex. It seems to just overwrite everything at `/path/to/miniconda3/envs/myenv`. After `quarto install tinytex`, any `quarto` command results in `-bash: /path/to/miniconda3/envs/myenv/bin/quarto: No such file or directory`. Perhaps we can fix this by patching the target directory for installing TinyTeX. I'd really prefer `tlmgr` to be conda-installable, though, instead of needing a two-step process of installing Quarto with `conda` and then installing TinyTex with `quarto`...

 `texlive-core-feedstock` [does not include `tlmgr`](https://github.com/conda-forge/texlive-core-feedstock/issues/27), which `quarto` relies on. Should we work on a new `tinytex-feedstock` for this?

How should users install a PDF engine? For now, I'm just doing a system install of TinyTeX! EDIT: This doesn't work, `quarto` still expects `tinytex` to be installed in the conda env's `bin` dir.

**Comment by cderv** [comment]
@mfisher87 thanks a lot for looking into this. I think we add an old issue that could be related to this. 

I'll look at the PR but it is really suprising behavior to have `quarto install tinytex` replaces the whole Quarto installation ! 🤯 

> Should we work on a new tinytex-feedstock for this?

I think this would be really good if we can do it ! I am happy to help build something. We maintain our releases at https://github.com/rstudio/tinytex-releases/ and if need I could add a trigger there for any new monthly release we are doing. 

> How should users install a PDF engine?

User should have a working LaTeX installation - We should support any distribution really, but we recommend the use of TinyTeX which is based on TeX Live. It contains some most used LaTeX package and is quite decent in download size. 

Also this is what works best with [Quarto PDF engine](https://quarto.org/docs/output-formats/pdf-engine.html#quarto-pdf-engine) which leverage `tlmgr` AFAIK

> EDIT: This doesn't work, quarto still expects tinytex to be installed in the conda env's bin dir.

There could be a path issue somewhere and maybe something wrong in Quarto side itself. 

I think it works this way in Quarto : 

* TinyTex is expected to be `~/.TinyTeX` on linux, `~/Library/TinyTeX` on mac and `%APPDATA%/TinyTeX` on windows. 
* If not found, then we check for TeX Live in PATH by executing `tlmgr --version`

So Quarto should not expect TinyTeX or `tlmgr` to be installed in the bin dir, unless conda env tweaks PATH or `~` maybe ?

**Comment by mfisher87** [comment]
>I'll look at the PR but it is really suprising behavior to have quarto install tinytex replaces the whole Quarto installation ! :exploding_head:

I also had an :exploding_head: moment when it happened to me! :rofl: This is a nasty outcome.

> There could be a path issue somewhere and maybe something wrong in Quarto side itself.
> 
> I think it works this way in Quarto :
> 
>     * TinyTex is expected to be `~/.TinyTeX` on linux, `~/Library/TinyTeX` on mac and `%APPDATA%/TinyTeX` on windows.
> 
>     * If not found, then we check for TeX Live in PATH by executing `tlmgr --version`
> 
> 
> So Quarto should not expect TinyTeX or `tlmgr` to be installed in the bin dir, unless conda env tweaks PATH or `~` maybe ?

Apologies if any of this is a re-hash of another post :)

Our patch is tweaking a function that returns the expected tinytex install dir. That patch may be misguided; the original goal was (as far as I can tell) to enable Quarto to manage a TinyTeX install that is specific to Quarto's conda environment. That goal is clearly in conflict with other expectations Quarto has about the TinyTex install location.

As changes are made to Quarto with those expectations about TinyTeX's location in mind, our attempts to patch in the support for isolated TinyTeX installs will keep breaking. So, I think either:

* `quarto-cli` needs to adopt support for TinyTeX installs in different locations (i.e. look for `tlmgr` on `PATH` and always use that one instead of looking for it at `tinyTexInstallDir()`?), or
* `quarto-feedstock` needs to stop trying to patch it in during the conda build process and always use `~/.TinyTeX`.

**Comment by cderv** [comment]
> Our patch is attempting to set it instead relative to CONDA_PREFIX so each conda-installed copy of Quarto has its own TinyTex install location.

This was my missing piece ! I understand now why this is conda packaging broken

> quarto-cli needs to adopt support for TinyTeX installs in different locations (i.e. look for tlmgr on PATH and always use that one instead of looking for it at tinyTexInstallDir()?)

I don't know if we can do that, because we want to prioritize TinyTeX over a system install, especially because installing TinyTeX won't always update the PATH (IIRC) 

I was thinking of another solution that would be for quarto to look into an env var for `tinyTexInstallDir()` and otherwise look for the default place. Or directly look for this specified path in the env var for where to look for `tlmgr`. We have a similar mechanism for the R package version of **tinytex** where you can set a `tinytex.tlmgr.path` option that we will use if provided. 

Would that help ?

**Comment by cderv** [comment]
> What about a [configuration](https://github.com/quarto-dev/quarto-cli/blob/main/configuration?rgh-link-date=2023-07-24T16%3A02%3A41Z) variable (something like export TINYTEX_INSTALL_PATH=${TINYTEX_INSTALL_PATH:-~/.TinyTeX}) we can set at build-time?

I think we only use those configurations for either dev workflow (update dependencies), for building package scripts or our run scripts. I mean I don't think any of the Quarto source code file (`.ts` file) will use one of this env variable. but here `TINYTEX_INSTALL_PATH` will need to be read by `tinyTexInstallDir()` - so it would not be different than a  runtime environment variable IMO. But maybe I am missing somethings.  This is that way because we don't package Tinytex or similar. 

I think I thought conda could have set an env var for the user - it seemed that you did that for `QUARTO_CONDA_PREFIX` in the patch. I was thinking no patches for tinytex code, but conda build would set the env var. 

But maybe not possible - I don't know a lot about conda 😅 

> Yes, since yesterday I'm starting to think the same :) At least until TinyTeX is conda-installable.

Probably the easiest and safest ! This would surely make also conda quarto package works more the same as other type of installation as none package TinyTex. 

> Should we work on a new tinytex-feedstock for this?

This is still an option TBH. Tinytex is its own distribution. We already provide it as chocolatey package on windows, and there is some people asking for it for winget. If that makes sense, a conda forge package could be helpful and quarto conda package could then depend on it maybe

**Comment by mfisher87** [comment]
>I think we only use those configurations for either dev workflow (update dependencies), for building package scripts or our run scripts. I mean I don't think any of the Quarto source code file (.ts file) will use one of this env variable. but here TINYTEX_INSTALL_PATH will need to be read by tinyTexInstallDir() - so it would not be different than a runtime environment variable IMO.

I was confused earlier, but now feeling more straightened out. Thanks! Still learning a lot about building for conda myself. Before doing `conda-forge` maintenance I had only built fairly trivial conda packages.

Since, based on our other discussions, it's not desirable for conda-packaged Quarto to install TinyTeX differently than non-conda-packaged Quarto, I think we can just restore the original behavior to install at `~/.TinyTeX`, assuming all testing goes OK.

Thinking out loud: When we can package TinyTeX for conda, let's revisit how to get Quarto to detect that. I think we'd probably want to make the TinyTex conda package an optional dependency of Quarto, so we'd need some way of checking if it's installed. An envvar in the above style may not be the best way, since they are set at conda-env activation time, and packages can be installed to the currently-active environment, and I don't think the activation scripts get re-run every time a new package is installed. I'm sure we can figure out some packaging magic to make that work. I'm not sure I fully understand the concerns about looking for `tlmgr` in `PATH` you mentioned earlier, but that would be one way to "detect" a conda-installed version.

>I think I thought conda could have set an env var for the user - it seemed that you did that for `QUARTO_CONDA_PREFIX` in the patch.

Thanks for prompting me to think about this more and look more closely at our build config. `QUARTO_CONDA_PREFIX` is a runtime var that's set at environment-activation time by a script in the conda package at `etc/conda/activate.d/quarto.sh`. This script is created [here](https://github.com/conda-forge/quarto-feedstock/blob/main/recipe/build.sh#L37-L47) during our build process. If we change our mind about conda-packaged Quarto installing TinyTeX into its own environment, we can have Quarto look for e.g. `QUARTO_TINYTEX_INSTALL_DIR` in the environment and set it to `QUARTO_CONDA_PREFIX/share/TinyTeX` during the conda build process.

> I was thinking no patches for tinytex code, but conda build would set the env var.

This would be much better -- anything we can do to get rid of patches is a huge win for me :)

>Probably the easiest and safest ! This would surely make also conda quarto package works more the same as other type of installation as none package TinyTex.

OK I think we have some decisions to go forward with. Do we agree on all of this?

* we resolve this issue by removing the patch which overrides the TinyTeX install dir from `~/.TinyTeX` to under `$CONDA_PREFIX`. After this change, all `quarto` installations will look for TinyTeX in the same place. (discussion: #24)

* we should mark broken and remove from conda-forge all the old packages affected by this bug (discussion: #25)

* we should strive to eventually package TinyTeX as a conda package, and at that point figure out how to get Quarto to play nicely with it. Then users can ensure they have Quarto with TeX by simply running a conda command instead of `conda install ...` followed by `quarto install ...`. (discussion: #26)
