### ISSUE TITLE
Remove broken builds

### ISSUE THREAD

**Issue by mfisher87** [conda-forge/quarto-feedstock#25]
Builds affected by #23 should probably be [marked broken and removed from conda-forge](https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages).

Should be bother backporting the fix to all the broken versions, or just remove them and move forward?

**Comment by cderv** [comment]
Probably ok to mark the old one as broken.

**Comment by mfisher87** [comment]
Just want to clarify, this would mean all these versions would disappear from `conda-forge`:

```
$ conda search "quarto<1.3.427"
Loading channels: done
# Name                       Version           Build  Channel             
quarto                       1.1.145      ha770c72_0  conda-forge         
quarto                       1.2.335      ha770c72_0  conda-forge         
quarto                       1.2.335      ha770c72_1  conda-forge         
quarto                       1.2.335      ha770c72_2  conda-forge         
quarto                       1.2.475      ha770c72_0  conda-forge         
quarto                       1.3.340      ha770c72_0  conda-forge         
quarto                       1.3.353      ha770c72_0  conda-forge         
quarto                       1.3.361      ha770c72_0  conda-forge         
```

There may be some projects that rely on specific versions (maybe because they are working around a bug, or because a later version changes some behavior they rely on), but don't use TinyTeX at all. If that's important, we should probably backport.

**Comment by cderv** [comment]
Oh I see thanks for detailing. 

We did not had much report of this issue. So maybe that was not that used among conda users, or they do use latest versions. 

> EDIT: Maybe a middle ground; just backport our fix to the latest 1.2.x and 1.1.x releases and get rid of everything else?

This seems ok. FWIW we do our patch generally on one version only. so if we found a bug that needs a patch we patch latest release only (so currently 1.3). 

With Quarto, currently it is advisable to use latest stable for your project. It is no only new feature but some bug we found along the way. 

Anyhow, I understand conda is used to fix environment so this also make sense to patch differently if this is easy enough to do

**Comment by mfisher87** [comment]
Builds to keep:

* v1.3.433-1 ([running](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=751637&view=results)
* v1.3.427-2 ([running](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=751644&view=results)

For other versions, let's play it by ear. Backporting this fix to other 1.3.x versions is easy if we decide we want them. 1.2.x would need a bit more testing.

**Comment by mfisher87** [comment]
Tested 1.2.475 conda package and it also overwrites the conda environment wholesale with TinyTeX. I guess this issue's been around longer than I thought. Maybe I'm actually innocent! :laughing:

I was hoping 1.2.x wasn't broken so we wouldn't have to remove them, but such is life.

**Comment by mfisher87** [comment]
Kicked off the process to resolve this ticket.

**Comment by mfisher87** [comment]
The conda-forge admins merged our request to remove the packages. I think they should be gone by end of today.

**Comment by mfisher87** [comment]
Verified:

```
conda search quarto
# Name                       Version           Build  Channel             
quarto                       1.3.427      ha770c72_2  conda-forge         
quarto                       1.3.433      ha770c72_1  conda-forge         
```
