### ISSUE TITLE
Contribute "external installer" patch to upstream

### ISSUE THREAD

**Issue by mfisher87** [conda-forge/quarto-feedstock#27]
I thought this had already been done, or a TODO maybe created, but I'm having trouble finding it.

This patch:

https://github.com/MattF-NSIDC/quarto-feedstock/blob/95a3bd9494f63a8d1eafd18395be9437e31943d3/recipe/0001-add-external-installer-command-for-packagers-like-co.patch

Should be incorporated upstream, IMO.

Upstream issue: https://github.com/quarto-dev/quarto-cli/issues/6575

Once this is completed :point_up: we need to remove our patch and leverage the new installer/preparer.

FYI: @cderv

**Comment by cderv** [comment]
Yes I think we could do that. 

@dragonstyle any reason that would prevent us to add this  new internal command for `quarto-bld` ?

**Comment by cderv** [comment]
I have open an issue to track on quarto-cli side. @mfisher87 do you want to do a PR ? 

Otherwise, I can probably do one and ping you for review.

**Comment by mfisher87** [comment]
Hey Christophe, I would love to but I think realistically, it would take me quite some time to get a PR ready. I don't get time at $DAY_JOB to do open source contributions unless I can tie them to a specific grant (looking for this to change, one way or another), and outside of work I'm committed to some group work on `conda-lock` and teaching Python for the next several weekends.

I would be happy to review if you wouldn't mind opening the PR!

**Comment by mfisher87** [comment]
Hey @cderv it is on my profile, but a bit buried. I'll make it more prominent :) `mfisher87@gmail.com`

**Comment by mfisher87** [comment]
Woops, after a tiny bit of further thought about this, it's actually @msarahan who should be credited for this change.

**Comment by cderv** [comment]
I put you both. You did the last modification with TinyTeX patch I believe.

**Comment by cderv** [comment]
So https://github.com/quarto-dev/quarto-cli/pull/6730 can be tested now. 

It requires 3 changes in there: 

* remove patch https://github.com/conda-forge/quarto-feedstock/blob/d4d59bead4669f274f75193d9434744f6dff4fcd/recipe/patches/0001-add-external-installer-command-for-packagers-like-co.patch#L32
* change to `prepare-external`
   https://github.com/conda-forge/quarto-feedstock/blob/d4d59bead4669f274f75193d9434744f6dff4fcd/recipe/build.sh#L35
* change to `prepare-external`
   https://github.com/conda-forge/quarto-feedstock/blob/d4d59bead4669f274f75193d9434744f6dff4fcd/recipe/bld.bat#L30

@mfisher87 something you can do to close the issue on side once after we merge  https://github.com/quarto-dev/quarto-cli/pull/6730 ?

**Comment by mfisher87** [comment]
Yes, happy to take the task of cleaning up the patches and build scripts and re-testing. May not be able to get to it until the weekend, though!

**Comment by cderv** [comment]
This was in fact opened since a long time at 
* https://github.com/quarto-dev/quarto-cli/issues/5444

And it was done recently at https://github.com/quarto-dev/quarto-cli/commit/0fea9ec2462db44e3e343b8eabe86950b90117fe

It just requires adjustment in the command name used.

**Comment by mfisher87** [comment]
Woops. Let's let the linked PR autoclose this.

**Comment by mfisher87** [comment]
Resolved in #36
