### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by mfisher87** [conda-forge/quarto-feedstock#35]
I hope to take a stab at it this weekend :)

**Comment by Benjas86** [comment]
I today popped a question over at the Quarto repo, and was pointed here. Will be great to have 1.4 in Conda-Forge, thank you

**Comment by mfisher87** [comment]
Agreed! I didn't have time last weekend like I hoped, but I have some time off from `$DAY_JOB` starting tomorrow. I'll post here or self-assign this issue when I get started.

If anyone else wants to pick this up before then, feel free! Please post so we we don't duplicate our efforts, and I'll assign the ticket to you and/or add you as a maintainer :)

**Comment by SaravananSathyanandhaQC** [comment]
@mfisher87 happy to take a look at this if you haven't found time to do so yet

**Comment by mfisher87** [comment]
Thanks so much for getting started on this! I indeed haven't yet found the time. Life is messy for me right now :sweat_smile: But hopefully tomorrow I can join you and we can work together on this! Taking a peek at the PR now :eyes:

**Comment by mfisher87** [comment]
Resolved in #36 . Thank you @SaravananSathyanandhaQC and @dragonstyle !

**Comment by Benjas86** [comment]
Thank you all, I know what I'll be doing at work today now!
