### ISSUE TITLE
`quarto-preview.js` missing in 1.4.557, 1.5.55

### ISSUE THREAD

**Issue by mfisher87** [conda-forge/quarto-feedstock#53]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
$ quarto preview
<...>
WARNING: No such file or directory (os error 2): readfile '/path/to/miniforge3/envs/envname/share/quarto/preview/quarto-preview.js'
$ ls -1 /path/to/miniforge3/envs/envname/share/quarto/preview/
jats/
quarto-preview.html
```

The .js file is present in 1.4.550; it was poor testing on my part for #50 I think. I was sure I'd tested preview :confused: 

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by mfisher87** [comment]
It's back in 1.5 (#52)

**Comment by cderv** [comment]
It should have been fixed for 1.4.557 following 
- https://github.com/quarto-dev/quarto-cli/pull/9805 as it was backported in https://github.com/quarto-dev/quarto-cli/commit/458da634f6c4b1588ebdb07a23dc7678f257b2d0
	````
	$ git tag --contains 458da63
	v1.4.555
	v1.4.556
	v1.4.557
	````

Maybe this needs specific adaptation in here ? 

This was due to specific dependencies problem in building the JS

**Comment by cderv** [comment]
I see it builds on the last conda forge run
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=970683&view=logs&j=ced5d8de-8227-5f3f-33a1-45cf1592c45a&t=f7bcb349-6dca-53ba-d88d-1d9963e119ba&l=2200

Not sure why not available then... 🤔

**Comment by mfisher87** [comment]
I'm really confused as well.

**Comment by mfisher87** [comment]
I was able to reproduce this in a local build. No other news :)

**Comment by cderv** [comment]
Do I understand correctly it is missing in latest stable 1.5 too when build for conda ? 

Is it missing on windows ? Or in all builds ? 

Maybe there is a copy issue - the file being built correctly but not copied to what creates the conda forge bundle 🤔

**Comment by mfisher87** [comment]
Thanks for helping look in to this! I'd love to be able to spend more time on this, but `$DAY_JOB` is taking a lot out of me and my time for open source contributions (volunteer and funded) has been much less than I'd like.

>Do I understand correctly it is missing in latest stable 1.5 too when build for conda ?

Correct, but not 1.4.550.

>Is it missing on windows ? Or in all builds ?

This still needs to be answered. I was able to confirm the Linux impact by downloading and unzipping tarballs from here: https://anaconda.org/conda-forge/quarto/files We should be able to do the same for the Mac/Win builds.

>Maybe there is a copy issue - the file being built correctly but not copied to what creates the conda forge bundle 🤔

This _sounds_ plausible! The logs show the preview build occurring. :thinking:

**Comment by mfisher87** [comment]
Restored a patch we used to hackily force the build of the preview script. I thought it was no longer needed, and removed it without testing thoroughly enough.

I apologize, but my time has been fairly limited and I don't yet understand why the upstream change didn't cause the script to be built the way I expected. Any help with this would be greatly appreciated so we can drop this patch.
